In [2]:
!nvidia-smi

Thu Oct  1 22:52:11 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 592.82                 Driver Version: 592.82         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2050      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8              1W /   50W |     119MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2444    C+G   ...Browser\Application\brave.exe      N/A      |
|    0   N/A  N/A           24820    C+G   ...Browser\Application\brave.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [3]:
!pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

In [4]:
!pip install --upgrade accelerate
!pip uninstall -y transforers accelerate
!pip install transformers accelerate

Collecting accelerate
  Downloading accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (2.5.3)
Requirement already satisfied: packaging>=20.0 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (26.3)
Requirement already satisfied: psutil in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: pyyaml in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (2.14.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (1.33.0)
Requirement already satisfied: safetensors>=0.4.3 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.70.1)
Requirement already satisfied: typing-extensions>=4.1.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.16.0)
Requirement already satisfied: anyio in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.15.1)
Requirement already satisfied: certifi in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.7.22)
Requirement already satisfied: httpcore==1.* in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.20)
Requirement already satisfied: h11>=0.16 in D:\Text-Summarizer\textS\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in D:\Text-Summarizer\textS\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in D:\Text-Summarizer\textS\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in D:\Text-Summarizer\textS\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Downloading accelerate-1.15.0-py3-none-any.whl (394 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.15.0

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/8a/4c/34f0450479d01195027260da68d8a3880683f1640c3ca5adf64acb3185f1/accelerate-1.15.0-py3-none-any.whl

Found existing installation: accelerate 1.15.0
Uninstalling accelerate-1.15.0:
  Successfully uninstalled accelerate-1.15.0

WARNING: Skipping transforers as it is not installed.

Requirement already satisfied: transformers in D:\Text-Summarizer\textS\Lib\site-packages (5.17.0)
Collecting accelerate
  Using cached accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (2.5.3)
Requirement already satisfied: packaging>=20.0 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in D:\Text-Summarizer\textS\Lib\site-packages (from transformers) (4.70.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: anyio in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.15.1)
Requirement already satisfied: certifi in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.20)
Requirement already satisfied: h11>=0.16 in D:\Text-Summarizer\textS\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: psutil in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in D:\Text-Summarizer\textS\Lib\site-packages (from accelerate) (2.14.0)
Requirement already satisfied: setuptools>=77.0.3 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in D:\Text-Summarizer\textS\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in D:\Text-Summarizer\textS\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in D:\Text-Summarizer\textS\Lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in D:\Text-Summarizer\textS\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in D:\Text-Summarizer\textS\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in D:\Text-Summarizer\textS\Lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in D:\Text-Summarizer\textS\Lib\site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in D:\Text-Summarizer\textS\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\Text-Summarizer\textS\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in D:\Text-Summarizer\textS\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Using cached accelerate-1.15.0-py3-none-any.whl (394 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.15.0

In [5]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (5.0.1)
Requirement already satisfied: numpy>=1.17 in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (2.5.3)
Requirement already satisfied: dill in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (3.0.6)
Requirement already satisfied: requests>=2.19.0 in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (2.34.2)
Requirement already satisfied: tqdm>=4.62.1 in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (4.70.1)
Requirement already satisfied: xxhash in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in D:\Text-Summarizer\textS\Lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2026.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (1.33.0)
Requirement already satisfied: packaging in D:\Text-Summarizer\textS\Lib\site-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in D:\Text-Summarizer\textS\Lib\site-packages (from datasets>=2.0.0->evaluate) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in D:\Text-Summarizer\textS\Lib\site-packages (from datasets>=2.0.0->evaluate) (25.0.1)
Requirement already satisfied: httpx<1.0.0 in D:\Text-Summarizer\textS\Lib\site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in D:\Text-Summarizer\textS\Lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in D:\Text-Summarizer\textS\Lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: anyio in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.15.1)
Requirement already satisfied: certifi in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2026.7.22)
Requirement already satisfied: httpcore==1.* in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in D:\Text-Summarizer\textS\Lib\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.20)
Requirement already satisfied: h11>=0.16 in D:\Text-Summarizer\textS\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in D:\Text-Summarizer\textS\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in D:\Text-Summarizer\textS\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.25.1)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\Text-Summarizer\textS\Lib\site-packages (from requests>=2.19.0->evaluate) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in D:\Text-Summarizer\textS\Lib\site-packages (from requests>=2.19.0->evaluate) (2.8.0)
Requirement already satisfied: colorama in D:\Text-Summarizer\textS\Lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Text-Summarizer\textS\Lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Text-Summarizer\textS\Lib\site-packages (from pandas->evaluate) (2026.4)
Requirement already satisfied: six>=1.5 in D:\Text-Summarizer\textS\Lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [6]:
from transformers import pipeline, set_seed
from datasets import load_dataset , load_from_disk
import matplotlib.pyplot as plt
from datasets import load_dataset
import pandas as pd
from datasets import load_dataset
import evaluate

from transformers import AutoModelForSeq2SeqLM , AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

nltk.download("punkt")

d:\Text-Summarizer\textS\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\anaya\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [8]:
from transformers import AutoModelForSeq2SeqLM , AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [9]:
model_ckpt = "google/pegasus-cnn_dailymail"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_pegasus = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
d:\Text-Summarizer\textS\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\anaya\.cache\huggingface\hub\models--google--pegasus-cnn_dailymail. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
d:\Text-Summarizer\textS\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\anaya\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 680/680 [00:00<00:00, 15888.31it/s]
[transformers] PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-cnn_dailymail
Key                                  | Status  |
-------------------------------------+---------+-
model.encoder.embed_positions.weight | MISSING |
model.decoder.embed_positions.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [10]:
# Load from Hugging Face Hub
dataset_samsum = load_dataset("knkarthick/samsum")

# Save the dataset to disk
dataset_samsum.save_to_disk("samsum_dataset")

d:\Text-Summarizer\textS\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\anaya\.cache\huggingface\hub\datasets--knkarthick--samsum. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 14731/14731 [00:00<00:00, 52433.56 examples/s]
Generating validation split: 100%|██████████| 818/818 [00:00<00:00, 32324.37 examples/s]
Generating test split: 100%|██████████| 819/819 [00:00<00:00, 57417.80 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 14731/14731 [00:00<00:00, 766370.13 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 818/818 [00:00<00:00, 132576.25 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 819/819 [00:00<00:00, 130722.85 examples/s]

In [11]:
dataset_samsum = load_from_disk("samsum_dataset")
print(dataset_samsum)

DatasetDict({
    train: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 14731
    })
    validation: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 818
    })
    test: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 819
    })
})

In [12]:
split_lengths = [len(dataset_samsum[split]) for split in dataset_samsum]

print(f"Split lengths:{split_lengths}")
print(f"Features: {dataset_samsum['train'].column_names}")
print("\nDialogue:")

print(dataset_samsum["test"][1]["dialogue"])

print("\nSummary")

print(dataset_samsum["test"][1]["summary"])

Split lengths:[14731, 818, 819]
Features: ['id', 'dialogue', 'summary']

Dialogue:
Eric: MACHINE!
Rob: That's so gr8!
Eric: I know! And shows how Americans see Russian ;)
Rob: And it's really funny!
Eric: I know! I especially like the train part!
Rob: Hahaha! No one talks to the machine like that!
Eric: Is this his only stand-up?
Rob: Idk. I'll check.
Eric: Sure.
Rob: Turns out no! There are some of his stand-ups on youtube.
Eric: Gr8! I'll watch them now!
Rob: Me too!
Eric: MACHINE!
Rob: MACHINE!
Eric: TTYL?
Rob: Sure :)

Summary
Eric and Rob are going to watch a stand-up on youtube.

In [13]:
def convert_examples_to_features(example_batch):
  input_encodings = tokenizer(example_batch['dialogue'] , max_length = 1024 ,truncation=True)
  target_encodings = tokenizer(
      text_target=example_batch["summary"],
      max_length=128,
      truncation=True
  )
  return{
      'input_ids' : input_encodings['input_ids'],
      'attention_mask': input_encodings['attention_mask'],
      'labels': target_encodings['input_ids']
  }

In [14]:
dataset_samsum_pt = dataset_samsum.map(convert_examples_to_features , batched = True)

Map: 100%|██████████| 14731/14731 [00:01<00:00, 7720.25 examples/s]
Map: 100%|██████████| 818/818 [00:00<00:00, 6904.73 examples/s]
Map: 100%|██████████| 819/819 [00:00<00:00, 7496.37 examples/s]

In [15]:
dataset_samsum_pt["train"]

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 14731
})

In [16]:
#Training

from transformers import DataCollatorForSeq2Seq

seq2seq_data_collector = DataCollatorForSeq2Seq(tokenizer , model = model_pegasus)

In [17]:
from transformers import TrainingArguments

trainer_args = TrainingArguments(
    output_dir="pegasus-samsum",
    num_train_epochs=1,
    warmup_steps=500,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    weight_decay=0.01,
    logging_steps=10,
    eval_strategy="steps",   # v5 syntax
    eval_steps=500,
    save_steps=1_000_000,
    gradient_accumulation_steps=16
)

In [ ]:
from transformers import TrainingArguments , Trainer

# trainer = Trainer(
#     model=model_pegasus,
#     args=trainer_args,
#     data_collator=seq2seq_data_collator,
#     train_dataset=dataset_samsum_pt["train"],
#     eval_dataset=dataset_samsum_pt["validation"]
# )

from transformers import DataCollatorForSeq2Seq

# Create a data collator for seq2seq tasks
seq2seq_data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model_pegasus
)

# Now you can safely pass it into Trainer
trainer = Trainer(
    model=model_pegasus,
    args=trainer_args,
    data_collator=seq2seq_data_collator,
    train_dataset=dataset_samsum_pt["train"],
    eval_dataset=dataset_samsum_pt["validation"]
)

In [22]:
trainer.train()

KeyboardInterrupt:

In [67]:
#Evaluation

def generate_batch_sized_chunks(list_of_elements, batch_size):
    """Split the dataset into smaller batches we can process simultaneously.
    Yield successive bacth-sized chunks from list_of_elements."""
    for i in range(0, len(list_of_elements), batch_size):
        yield list_of_elements[i : i + batch_size]

def calculate_metric_on_test_ds(dataset, metric, model, tokenizer,
                                batch_size=16, device=device,
                                column_text="dialogue",
                                column_summary="summary"):
    article_batches = list(generate_batch_sized_chunks(dataset[column_text], batch_size))
    target_batches = list(generate_batch_sized_chunks(dataset[column_summary], batch_size))

    for article_batch, target_batch in tqdm(
        zip(article_batches, target_batches), total=len(article_batches)
    ):
        inputs = tokenizer(article_batch, max_length=1024, truncation=True,
                           padding="max_length", return_tensors="pt")

        summaries = model.generate(
            input_ids=inputs["input_ids"].to(device),
            attention_mask=inputs["attention_mask"].to(device),
            length_penalty=0.8,
            num_beams=8,
            max_length=128
        )
        '''parameter for length penalty ensures that the model does not generate sequences'''

        # Decode generated summaries
        decoded_summaries = tokenizer.batch_decode(summaries, skip_special_tokens=True)
        # decoded_summaries= [d.replace(""," ") for d in decoded_summaries]

        # Add batch to metric
        metric.add_batch(predictions=decoded_summaries, references=target_batch)

    # Compute and return ROUGE scores
    score = metric.compute()
    return score

In [68]:
rouge_names = ["rouge1", "rouge2", "rougeL", "rougeLsum"]
rouge_metric = evaluate.load("rouge")

In [72]:
score = calculate_metric_on_test_ds(
    dataset_samsum_pt["test"], rouge_metric, trainer.model, tokenizer, batch_size=2 , column_text="dialogue" , column_summary="summary"
)
rouge_dict = {rn: score[rn] for rn in rouge_names}
pd.DataFrame(rouge_dict, index=["pegasus"])

100%|██████████| 410/410 [23:30<00:00,  3.44s/it]

           rouge1    rouge2    rougeL  rougeLsum
pegasus  0.447005  0.215296  0.353888   0.353957

In [73]:
# Save model
model_pegasus.save_pretrained("pegasus-samsum-model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [74]:
#Save tokenizer
tokenizer.save_pretrained("tokenizer")

('tokenizer/tokenizer_config.json', 'tokenizer/tokenizer.json')

In [75]:
# Load

tokenizer = AutoTokenizer.from_pretrained("/content/tokenizer")

In [83]:
# Prediction

gen_kwargs = {"length_penalty": 0.8, "num_beams": 8, "max_length": 128}

sample_text = dataset_samsum_pt["test"][0]["dialogue"]
reference = dataset_samsum_pt["test"][0]["summary"]

# Encode the input dialogue and move to GPU if available
inputs = tokenizer(
    sample_text,
    return_tensors="pt",
    truncation=True,
    padding="max_length",
    max_length=1024
).to(trainer.model.device)   # match model device

# Generate summary
summary_ids = trainer.model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    **gen_kwargs
)

# Decode the generated summary
model_summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Dialogue:")
print(sample_text)

print("\nReference Summary:")
print(reference)

print("\nModel Summary:")
print(model_summary)

Dialogue:
Hannah: Hey, do you have Betty's number?
Amanda: Lemme check
Hannah: <file_gif>
Amanda: Sorry, can't find it.
Amanda: Ask Larry
Amanda: He called her last time we were at the park together
Hannah: I don't know him well
Hannah: <file_gif>
Amanda: Don't be shy, he's very nice
Hannah: If you say so..
Hannah: I'd rather you texted him
Amanda: Just text him 🙂
Hannah: Urgh.. Alright
Hannah: Bye
Amanda: Bye bye

Reference Summary:
Hannah needs Betty's number but Amanda doesn't have it. She needs to contact Larry.

Model Summary:
Amanda has Betty's number. She can't find Betty's number. He called her last time they were at the park together. Hannah doesn't know him well.